[project]
name = "ai-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=6.14.0",
    "openai>=2.38.0",
    "pdfreader>=0.1.15",
    "pydantic>=2.13.4",
    "pypdf>=6.12.1",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
]
